### ISSUE TITLE
wget2

### ISSUE THREAD

**Issue by God-damnit-all** [1480c1/media-autobuild_suite#4]
I've been holding off on making this request since it seems like a fairly major undertaking, but I'm getting more annoyed every day at how much harder it's getting to grab things off the net. With the current crisis, I've been doing a fair bit of data hoarding. So, I'm wondering if there's any possibility of including [wget2](https://gitlab.com/gnuwget/wget2) into the suite.

I'm not sure it entirely fits the theme since it's not directly media-related, but wget has been showing its age, and when it comes to _acquiring_ media, it's getting harder and harder to properly crawl the web without running into issues. You can get wget2 running in WSL and cygwin, but network compatibility is where these things are weakest, and you'll occasionally run into strange issues that won't occur in say, an Ubuntu VM.

[This issue](https://gitlab.com/gnuwget/wget2/issues/482) has someone claiming it can be built with the exception of libhttpd, but doesn't go into how (someone even asked and didn't get a response) and they have no personal fork of the repo. Through maintaining media-autobuild_suite you've become an expert at getting stuff made with Linux in mind to static compile into a single Windows file, and I can think of no one better to do this.

**Comment by God-damnit-all** [comment]
I'm starting to think I may have actually requested this of you in the past and if I have, I apologize. My memory is not the greatest.

**Comment by 1480c1** [comment]
Nah, this is the first time.

I'll look into it, but no promises

**Comment by 1480c1** [comment]
Are you looking into getting it into mabs, or separate?

**Comment by God-damnit-all** [comment]
I think it would be most convenient as part of mabs, but I'd be happy with it separate too.

**Comment by 1480c1** [comment]
I am currently working on this, but I need to fix my local msys2 environment since I was testing some other things and broke it, so it may take a little bit more time.

I am planning to make it a bash script that you just copy to the mabs root dir and run through mintty, that way it can just put it in the same place as the rest of your tools

The main reason why I am not planning to add it to mabs is that it doesn't seem like a tool that matches what mabs would provide (although there might be an argument for it since we have an option to build curl)

**Comment by 1480c1** [comment]
https://gist.github.com/1480c1/6f1933af2c0f3d37d70dc8386f2e08ba

A tentative script that "works on my machine", you can copy it to anywhere and run it in mintty, you can either double click mintty and run `./path/to/wget2.sh` or drag and drop `wget2.sh` on top of mintty

**Comment by God-damnit-all** [comment]
Hum.

```
├ lzlib-1.9.tar.lz  .................................... [Downloaded] ((OR [File up-to-date]))
Running configure in .
/build/media-suite_helper.sh: line 1424: ./configure: No such file or directory
Running install in .
make: *** No rule to make target 'install'.  Stop.
make: *** No rule to make target 'install'.  Stop.
├ /local64/include/lzlib.h  .................................. [Not found]
└ .  ............................................................ [Failed]
```
It seems like it's not extracting, but I tried extracting it manually, creating a directory named lzlib-1.9, same result. Tried renaming the directory to lzlib, same result.

**Comment by 1480c1** [comment]
did you update the suite? I added a change to the main scripts that's needed

**Comment by God-damnit-all** [comment]
Oops! I didn't think to do that because I had just updated it very recently.

It went smoothly, no errors that I can see. I'm very impressed! Thank you so much.

**Comment by God-damnit-all** [comment]
Oh, I do have one question. In the output, there's wget2 and wget2_noinstall, what is the difference between them?

**Comment by 1480c1** [comment]
Based on what I can tell, literally nothing since they both contain the exact same code, however, it seems one is not actually supposed to be installed with `make install` on normal Linux systems, but because the libtool stuff in msys2 and mingw-w64 is a bit weird, it doesn't understand the `--no-install` option that was passed by wget2

**Comment by God-damnit-all** [comment]
Hmm okay. They don't hash quite the same but I guess the difference is so minimal it doesn't matter. I guess the safe bet is using the no install version though. Thanks again.

**Comment by God-damnit-all** [comment]
While I initially thought this was working, having tried it out for a bit, I think it isn't able to recognize when it's actually started/stopped a download. It keeps trying to retry anything that redirects it, over and over, interrupting its own download. A dropbox link with ?dl=1 at the end is a good example of this.

**Comment by 1480c1** [comment]
Hmm I'll look into it in a bit

**Comment by 1480c1** [comment]
Can you give me an example link or command line? I was able to download a file from dropbox after sharing and modifying the dl=0 to dl=1, although the name got messed up (`'01 %E3%83%8F%E3%83%8A%E3%83%9F%E3%82%BA%E3%82%AD.m4a%3Fdl=1'` `'01 %E3%83%8F%E3%83%8A%E3%83%9F%E3%82%BA%E3%82%AD.m4a%3Fdl=1.1'` `'01 %E3%83%8F%E3%83%8A%E3%83%9F%E3%82%BA%E3%82%AD.m4a%3Fdl=1.1.1'`, I'm assuming it's because of the basename of the URL `01%20%E3%83%8F%E3%83%8A%E3%83%9F%E3%82%BA%E3%82%AD.m4a`)
